### ISSUE TITLE
请教一下，前端组件如何部署的问题

### ISSUE THREAD

**Issue by doudou-dream** [deatil/larke-admin-signcert#2]
我先现在已经 composer require larke/sign-cert 安装成功，后台页面也已经操作了安装更新按钮
![image](https://user-images.githubusercontent.com/24222969/105572971-3f649a00-5d95-11eb-8e4c-e6b5ec257ea9.png)
![image](https://user-images.githubusercontent.com/24222969/105572912-eeed3c80-5d94-11eb-8cc8-9b94fc8a1c27.png)
请问前端文件放到这里之后如何加入路由显示呢？

**Comment by deatil** [comment]
确定菜单数据添加后，只需要退出当前的脚本重新编译下就可以了

**Comment by doudou-dream** [comment]
前端从哪个目录文件下添加菜单呢，不好意思，前端刚接触不是很了解

**Comment by deatil** [comment]
> 前端从哪个目录文件下添加菜单呢，不好意思，前端刚接触不是很了解

elementui的是在router目录，扩展不需要手动加

**Comment by doudou-dream** [comment]
> > 前端从哪个目录文件下添加菜单呢，不好意思，前端刚接触不是很了解
> 
> 
> 
> elementui的是在router目录，扩展不需要手动加

那如截图所示，我只需要再重新编译一下就可以是么，我重新编译以后没有出现新的扩展菜单，怎么排查一下问题出在哪呢，是我放的位置不对么

**Comment by deatil** [comment]
> > > 前端从哪个目录文件下添加菜单呢，不好意思，前端刚接触不是很了解
> > 
> > 
> > elementui的是在router目录，扩展不需要手动加
> 
> 那如截图所示，我只需要再重新编译一下就可以是么，我重新编译以后没有出现新的扩展菜单，怎么排查一下问题出在哪呢，是我放的位置不对么

看下菜单管理和权限菜单那两个里面有没有扩展的菜单信息
